### ISSUE TITLE
Continue to support rebar2

### ISSUE THREAD

**Issue by oubiwann** [erlsci/iso8601#28]
Right now, only `rebar3` is being used on Travis CI. It would be good to make sure we're not breaking anything with rebar2 users. We can do this with Travis CI environments ...

**Comment by oubiwann** [comment]
I'm not really sure how important this is these days ...

**Comment by tsloughter** [comment]
I think you can close this one now :)

**Comment by oubiwann** [comment]
Hahaha -- indeed ;-)
