### ISSUE TITLE
Version error in the documentation

### ISSUE THREAD

**Issue by HernanRivasAcosta** [erlsci/iso8601#30]
On the readme it says:

> 
> Add it to your rebar.config deps:
> 
> ``` {iso8601, ".*", {git, "https://github.com/erlsci/iso8601.git", {tag, "1.2.0"}}} ```
> Or for rebar3:
> 
> ``` {iso8601, {git, "https://github.com/erlsci/iso8601.git", {tag, "1.2.0"}}} ```

When the version string should be "1.2".

**Comment by oubiwann** [comment]
Done.
