### ISSUE TITLE
Bad spec definition causes dialyzer error

### ISSUE THREAD

**Issue by cabol** [erlsci/iso8601#36]
The spec located in the file https://github.com/erlsci/iso8601/blob/master/src/iso8601.erl#L41 is wrong. The function allows either `string()` or  `binary()`, so probably it is a better option to use `iodata()` instead. This causes that dialyzer fails.

**Comment by oubiwann** [comment]
Thanks for the heads-up!

**Comment by oubiwann** [comment]
I've updated the spec for `parse` and `parse_exact`. Let me know if that fixes it for you.

**Comment by cabol** [comment]
Great! Thanks!  :)

**Comment by oubiwann** [comment]
I'm going to go ahead and close this -- if the fix didn't work, feel free to reopen!
