### ISSUE TITLE
Images stored in 'priv' directory.

### ISSUE THREAD

**Issue by gotthardp** [erlsci/iso8601#37]
The `priv/images` directory contains logos referenced in the README. The `priv` directory is usually used for storing data required to run the software, so the rebar tool includes content of the `priv` directory in a binary release (whereas the README.md itself is not included). The 3MB image (logo-large) makes the binary release file unnecessarily large, becase the logos aren't really required at run-time.

Would it be possible to store the images in some other directory e.g. `doc/images`? It wouldn't impact anything (I guess) and my release package would get significantly smaller.

**Comment by oubiwann** [comment]
Absolutely -- will do that tonight for you.

**Comment by oubiwann** [comment]
Ugh! I was traveling, and forgot -- doing it now ...

**Comment by oubiwann** [comment]
Done! Should be all set -- when you confirm, we can close this ticket :-)

Thanks for reporting this!

**Comment by oubiwann** [comment]
Also: I've bumped the micro version -- this is one of a few bug fixes since the last release. I've created a new tag and pushed the latest to Hex.pm.

**Comment by gotthardp** [comment]
It works! Thank you for so fast response and for bumping the release number!
