### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlsci/iso8601#52]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by oubiwann** [comment]
yeah, totally -- all my new projects use GA; I'll make this change here for the last five versions of Erlang ...

**Comment by paulo-ferraz-oliveira** [comment]
I pull requested for this. I read only the first few characters in the notification ("yeah, totally") and jumped to it 😞

**Comment by oubiwann** [comment]
Hahaha! No worries -- I can merge, and if there's other stuff I like to have added, I'll update in a separate commit ;-)
