### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlsci/iso8601#57]
Would it be possible to tag a release, here and in Hex.pm?

Many thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Bump.

**Comment by paulo-ferraz-oliveira** [comment]
Bump. @oubiwann

**Comment by paulo-ferraz-oliveira** [comment]
Bump. @oubiwann

**Comment by paulo-ferraz-oliveira** [comment]
Bump. (I'm starting to believe it's possible this project's "dead").

**Comment by paulo-ferraz-oliveira** [comment]
No wait, stuff was happening in Feb. So, I'll be patient some more...

**Comment by oubiwann** [comment]
Sorry, didn't see this -- thanks for the ping on Slack. 

On it!

**Comment by oubiwann** [comment]
Something's wrong with my hex.pm account, but until I get that sorted, you'll at least be able to pull from a new tag on Github ...

**Comment by oubiwann** [comment]
Done! 

https://github.com/erlsci/iso8601/releases/tag/1.3.2

**Comment by paulo-ferraz-oliveira** [comment]
Thanks. Will also wait on that Hex package 👀
